/** Generate a shell hook script for Claude Code session capture */
export function generateHookScript(scope: 'user' | 'project' | 'enterprise'): string {
  const scopeComment = {
    user: '# User-scoped hook: captures memory candidates from all sessions',
    project: '# Project-scoped hook: captures memory candidates for this repo only',
    enterprise: '# Enterprise-scoped hook: enforced capture with tenant isolation',
  };

  return `#!/usr/bin/env bash
${scopeComment[scope]}
# Generated by @qmd-team-intent-kb/claude-runtime
# Scope: ${scope}
set -euo pipefail

TEAMKB_BASE="\${TEAMKB_BASE_PATH:-$HOME/.teamkb}"
SPOOL_DIR="$TEAMKB_BASE/spool"
DATE=$(date -u +%Y-%m-%d)
SPOOL_FILE="$SPOOL_DIR/spool-$DATE.jsonl"

mkdir -p "$SPOOL_DIR"

# Read candidate JSON from stdin and append to daily spool
if [ -t 0 ]; then
  echo "Error: No input on stdin. Pipe a memory candidate JSON to this script." >&2
  exit 1
fi

cat >> "$SPOOL_FILE"
`;
}
